version: "3.7"

networks:
  test_network:
    driver: bridge

services:
  tetest:
    container_name: app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mysql
    env_file: .env
    networks:
      - test_network

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=testpass
      - MYSQL_DATABASE=tetest
      - MYSQL_ROOT_PASSWORD=testpass
    volumes:
      - mysql:/var/lib/mysql
      - ./db/baseline.sql:/docker-entrypoint-initdb.d/baseline.sql:ro
    networks:
      - test_network


volumes:
  tetest:
  mysql:

